apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  name: input-artifact-git
  namespace: argo
spec:
  arguments: {}
  entrypoint: git-clone
  templates:
  - container:
      args:
      - git status && ls && mvn clean install
      command:
      - sh
      - -c
      image: allardkrings/riscv64-maven
      name: ""
      resources: {}
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: dockersock
      workingDir: /src
    inputs:
      artifacts:
      - git:
#create a secret containing your git username and pasword and replace the name below:
          usernameSecret:
            key: username
            name: <git-secret>
          passwordSecret:
            key: password
            name: <git-secret>
#add your git-repo in the line below:
          repo: https://<git-repo to clone from>
        name: argo-source
        path: /src
    metadata: {}
    name: git-clone
    outputs: {}
  volumes:
# we mount the docker.sock from the host to build and push the image:
  - hostPath:
      path: /var/run/docker.sock
    name: dockersock
